/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomBadge: typeof import('./components/element/CustomBadge.vue')['default']
    CustomButton: typeof import('./components/element/CustomButton.vue')['default']
    CustomCard: typeof import('./components/element/CustomCard.vue')['default']
    CustomCol: typeof import('./components/element/CustomCol.vue')['default']
    CustomDatePicker: typeof import('./components/element/CustomDatePicker.vue')['default']
    CustomDialog: typeof import('./components/element/CustomDialog.vue')['default']
    CustomDropdown: typeof import('./components/element/CustomDropdown.vue')['default']
    CustomEmpty: typeof import('./components/element/CustomEmpty.vue')['default']
    CustomForm: typeof import('./components/element/CustomForm.vue')['default']
    CustomFormItem: typeof import('./components/element/CustomFormItem.vue')['default']
    CustomIcon: typeof import('./components/element/CustomIcon.vue')['default']
    CustomInput: typeof import('./components/element/CustomInput.vue')['default']
    CustomInputNumber: typeof import('./components/element/CustomInputNumber.vue')['default']
    CustomOption: typeof import('./components/element/CustomOption.vue')['default']
    CustomPagination: typeof import('./components/element/CustomPagination.vue')['default']
    CustomRadioButton: typeof import('./components/element/CustomRadioButton.vue')['default']
    CustomRadioGroup: typeof import('./components/element/CustomRadioGroup.vue')['default']
    CustomRow: typeof import('./components/element/CustomRow.vue')['default']
    CustomSelect: typeof import('./components/element/CustomSelect.vue')['default']
    CustomSwitch: typeof import('./components/element/CustomSwitch.vue')['default']
    CustomTable: typeof import('./components/element/CustomTable.vue')['default']
    CustomTableColumn: typeof import('./components/element/CustomTableColumn.vue')['default']
    CustomTag: typeof import('./components/element/CustomTag.vue')['default']
    CustomTooltip: typeof import('./components/element/CustomTooltip.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MoneyInput: typeof import('./components/element/MoneyInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDrawer: typeof import('./components/SettingsDrawer.vue')['default']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
